version: '3'
services:
  web:
    build:
      context: ./docker/web
    ports:
      - "3000:80"
    volumes:
      - ./webroot:/var/www/html
      - ./docker/web/apache/httpd.conf:/etc/httpd/conf/httpd.conf
    restart: always

    