version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "3000:3000"
    working_dir: "/var/www/html/project"
    volumes:
      - "./project:/var/www/html/project"
      - node_modules_volume:/var/www/html/project/node_modules
    tty: true
volumes:
  node_modules_volume: